name: Auto-approve dependency PRs

on:
  pull_request_target:
    branches:
      - dev

permissions:
  pull-requests: write

jobs:
  auto-approve:
    if: github.actor == 'renovate[bot]' || github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363 # v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
