name: Test

on:
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: 22
      - name: Cache dependencies
        id: cache-depends
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: '**/node_modules'
          key: depends-${{ hashFiles('yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-depends.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --check-files
      - name: Lint
        run: yarn lint
      - name: Build
        run: yarn build
